{
 "title": "Kubernetes Dashboard",
 "description": "Summary metrics about kube-state-metrics v2 version(https://github.com/kubernetes/kube-state-metrics); Referenced 6417",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerRequest = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_container_resource_requests{resource=\"cpu\",pod=~\"$deployment.*\", namespace=~\"$namespace\"}) by (pod, container))\r\n)\r\ncontainerRequest * 1000 ",
     "legendFormat": "request: {{ deployment }}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerLimit = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"$deployment.*\", namespace=~\"$namespace\"}) by (pod, container))\r\n)\r\ncontainerLimit * 1000 ",
     "legendFormat": "limit: {{ deployment }}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerUsage = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) sum(rate(container_cpu_usage_seconds_total{pod=~\"$deployment.*\",namespace=~\"$namespace\"}[$__rate_interval])) by (pod,container))\r\n)\r\ncontainerUsage * 1000 ",
     "legendFormat": "usage: {{ deployment }}"
    }
   ]
  },
  {
   "title": "Memory Usage Deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerRequest = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_container_resource_requests{resource=\"memory\",pod=~\"$deployment.*\", namespace=~\"$namespace\",container!=\"istio-proxy\"}) by (container, pod))\r\n)\r\ncontainerRequest",
     "legendFormat": "request: {{ deployment }}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerLimit = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$deployment.*\", namespace=~\"$namespace\"}) by (container, pod))\r\n)\r\ncontainerLimit",
     "legendFormat": "limit: {{ deployment }}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment) \r\n    ),\r\n    containerUsage = avg by (deployment, container) (deploymentName * on (pod) group_right(deployment) avg(container_memory_working_set_bytes{pod=~\"$deployment.*\",namespace=~\"$namespace\"}) by (container, pod))\r\n)\r\ncontainerUsage",
     "legendFormat": "usage: {{ deployment }}"
    }
   ]
  },
  {
   "title": "Pods State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "WITH(\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\n    deploymentName = avg by (deployment, pod) (\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\n    ),\n    podStatusPhase = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_status_phase{commonVars, pod=~\"$deployment.*\", phase=\"Running\"}) by (pod, phase))\n)\npodStatusPhase",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "WITH(\r\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\r\n    deploymentName = avg by (deployment, pod) (\r\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \r\n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\r\n    ),\r\n    podStatusPhase = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_status_phase{commonVars, pod=~\"$deployment.*\", phase=\"Pending\"}) by (pod, phase))\r\n)\r\npodStatusPhase",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "WITH(\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\n    deploymentName = avg by (deployment, pod) (\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\n    ),\n    podStatusClbo = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) increase(kube_pod_container_status_restarts_total{commonVars, pod=~\"$deployment.*\"}[5m]))\n)\npodStatusClbo ",
     "legendFormat": "CrashLoopBackOff"
    },
    {
     "expr": "WITH(\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\n    deploymentName = avg by (deployment, pod) (\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\n    ),\n    podStatusPhase = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_status_phase{commonVars, pod=~\"$deployment.*\", phase=\"Failed\"}) by (pod, phase))\n)\npodStatusPhase",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "WITH(\n    commonVars = {cluster=\"$cluster\", namespace=\"$namespace\"},\n    deploymentName = avg by (deployment, pod) (\n        label_replace(kube_pod_owner{commonVars, owner_kind=\"ReplicaSet\", owner_name=~\"$deployment.*\"}, \"replicaset\", \"$1\", \"owner_name\", \"(.*)\") \n        * on (replicaset) group_left(deployment) avg(label_replace(kube_replicaset_owner{commonVars, owner_name=~\"$deployment\"}, \"deployment\", \"$1\", \"owner_name\", \"(.*)\")) by (replicaset, deployment)\n    ),\n    podStatusPhase = sum by (deployment, phase) (deploymentName * on (pod) group_right(deployment) avg(kube_pod_status_phase{commonVars, pod=~\"$deployment.*\", phase=\"Unknown\"}) by (pod, phase))\n)\npodStatusPhase",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "RED Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPM",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{pod=~\"$deployment.*\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Per Minute",
     "type": "timeseries",
     "description": "get rate of http_request_duration_seconds_count for last 30 minutes at 15 seconds resolution",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 9 },
     "targets": [
      {
       "expr": "sum by (pod, handler) (increase(http_request_duration_seconds_count{pod=~\"$deployment.*\"}[1m]))",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Errors Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(sum(rate(http_request_duration_seconds_count{pod=~\"$deployment.*\", code=~\"4..\"}[1m])) by (code, handler, method, pod)) / (sum(rate(http_request_duration_seconds_count[1m])) by (code, handler, method, pod)) * 100",
       "legendFormat": "{{code}}: {{handler}} {{ method }}"
      },
      {
       "expr": "(sum(rate(http_request_duration_seconds_count{pod=~\"$deployment.*\", code=~\"5..\"}[1m])) by (code, handler, method, pod)) / (sum(rate(http_request_duration_seconds_count[1m])) by (code, handler, method, pod)) * 100",
       "legendFormat": "{{code}}: {{handler}} {{ method }}"
      }
     ]
    },
    {
     "title": "HTTP Latency 95p",
     "type": "timeseries",
     "description": "in Seconds",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n    0.95, \r\n    sum by (handler, method, le) (rate(http_request_duration_seconds_bucket{pod=~\"$deployment.*\"}[10m]))\r\n)",
       "legendFormat": "{{method}}: {{handler}} "
      }
     ]
    },
    {
     "title": "HTTP Latency 50p",
     "type": "timeseries",
     "description": "in Seconds",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\r\n    0.50, \r\n    sum by (handler, method, le) (rate(http_request_duration_seconds_bucket{pod=~\"$deployment.*\"}[10m]))\r\n)",
       "legendFormat": "{{method}}: {{handler}}"
      }
     ]
    },
    {
     "title": "Concurrent Request Per 10 Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_inflight{pod=~\"$deployment.*\"}[10s])) by (handler)",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster Pod Requested",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{cluster=~\"$cluster\",node=~\"$node\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Cluster CPU Requested",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})/ sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Cluster Memory  Requested",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"}) / sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Cluster Pod Capacity",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",node=~\"$node\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_pod_info{node=~\"$node\",cluster=~\"$cluster\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster CPU Capacity",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
       "legendFormat": "limited"
      }
     ]
    },
    {
     "title": "Cluster Mem Capacity",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
       "legendFormat": "limited"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Node NotReady",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status=\"false\"}==1",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node Pressure",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"DiskPressure\",cluster=~\"$cluster\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      },
      {
       "expr": "kube_node_status_condition{condition=\"MemoryPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      },
      {
       "expr": "kube_node_status_condition{condition=~\"PIDPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
       "legendFormat": "{{node}} {{condition}}"
      }
     ]
    },
    {
     "title": "node number",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ statefulset}}"
      }
     ]
    },
    {
     "title": "Statefulset replicas",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=~\"$cluster\"}/kube_statefulset_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"}*100",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods restart in 30m",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m])>1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Evicted",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_status_reason{cluster=~\"$cluster\",namespace=~\"$namespace\", reason=\"Evicted\"}==1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\" ,cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "hpa",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "current_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "max_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_min_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "min_{{hpa}}"
      }
     ]
    },
    {
     "title": "total-hpa-current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_hpa_status_current_replicas{hpa=~\".*\"})",
       "legendFormat": "kube_hpa_status_current_replicas"
      }
     ]
    },
    {
     "title": "current==max",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_max_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    },
    {
     "title": "current==min",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_min_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\",cluster=~\"$cluster\"})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
     "targets": [
      {
       "expr": "kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"}>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "pvc is bound",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc is not bound",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}