{
 "title": "Istio",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(istio_requests_total, job)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(istio_request_duration_milliseconds_count{job=~\"$job\"}, destination_app)"
    }
   },
   {
    "name": "status",
    "query": "success : [2-3].*,error : [4-5].*"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, sum(\n        rate(\n            istio_request_duration_milliseconds_bucket\n            {\n                destination_app=~\"$app\",\n                response_code=~\"$status\",\n                job=~\"$job\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(\n    0.90, sum(\n        rate(\n            istio_request_duration_milliseconds_bucket\n            {\n                destination_app=~\"$app\",\n                response_code=~\"$status\",\n                job=~\"$job\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n    0.50, sum(\n        rate(\n            istio_request_duration_milliseconds_bucket\n            {\n                destination_app=~\"$app\",\n                response_code=~\"$status\",\n                job=~\"$job\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(istio_requests_total{destination_app=~\"$app\", response_code=~\"$status\", job=~\"$job\"}[30s])",
     "legendFormat": "{{ destination_app }}-{{ destination_canonical_revision }}"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_app=~\"$app\", response_code=~\"$status\", job=~\"$job\"}[30s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Availability (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        istio_requests_total\n        {\n            destination_app=~\"$app\",\n            response_code!~\"[4-5].*\",\n            job=~\"$job\"\n        }[1m])) by (destination_app) /\nsum(\n    rate(\n        istio_requests_total\n        {\n            destination_app=~\"$app\",\n            job=~\"$job\"\n        }[1m])) by (destination_app)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  }
 ]
}